services:
  proj:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - projDB
    networks:
      - reseauProj
  projDB:
    build: ./postgresDocker/
    ports:
      - "5432:5432"
    restart: always
    networks:
      - reseau
    volumes:
      - db-dataProj:/var/lib/postgresql/data
volumes:
  db-dataProj:
networks:
  reseauProj: