services:
  proj:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - projdb
    networks:
      - reseauproj
  projdb:
    build: ./postgresDocker/
    ports:
      - "5433:5432"
    restart: always
    networks:
      - reseauproj
    volumes:
      - db-dataproj:/var/lib/postgresql/data
volumes:
  db-dataproj:
networks:
  reseauproj: